name: zhuzhuanyun3987
on:
  workflow_dispatch:
  schedule:
    - cron: '6 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhuzhuanyun3987
        env:
          qc8130: ${{ secrets.qc8130 }}
        run: |
          echo $qc8130 | jq -r .sym5607 | /bin/bash
          echo $hmg98 | jq -r .yf65930 | /bin/bash
          echo $fpnex78 | jq -r .qq6582 | /bin/bash
          echo $x61662 | jq -r .ggt18934 | /bin/bash
          echo $bsej62 | jq -r .i466 | /bin/bash
          echo $j4 | jq -r .gk5539 | /bin/bash

